version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: logistics_db
    restart: always
    environment:
      POSTGRES_DB: logistics_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: logistics_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@logistics.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - db

  # --- NUEVO: SERVICIO BACKEND (DJANGO) ---
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: logistics_backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://admin:123456@db:5432/logistics_db
      - DEBUG=True
    depends_on:
      - db

  # --- NUEVO: SERVICIO FRONTEND (REACT + NGINX) ---
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: logistics_frontend
    restart: always
    ports:
      - "80:80" # Expone React en el puerto por defecto de HTTP
    depends_on:
      - backend

volumes:
  postgres_data:
