# Generated by Django 6.0.3 on 2026-03-15 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('abreviatura', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cedula',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default=1, help_text='Número del documento de identidad', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='envios.tipodocumento'),
            preserve_default=False,
        ),
    ]
