# Generated by Django 6.0.3 on 2026-03-15 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envios', '0002_tipodocumento_remove_cliente_cedula_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bodega',
            table='bodega',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='envio',
            table='envio',
        ),
        migrations.AlterModelTable(
            name='puerto',
            table='puerto',
        ),
        migrations.AlterModelTable(
            name='tipodocumento',
            table='tipo_documento',
        ),
        migrations.AlterModelTable(
            name='tipologistica',
            table='tipo_logistica',
        ),
        migrations.AlterModelTable(
            name='tipoproducto',
            table='tipo_producto',
        ),
    ]
